jenkins:
  systemMessage: |
    Jenkins configured by JCasC. CI/CD pipeline for CI_CD_APP_VERSION.
  numExecutors: 2
  authorizationStrategy: loggedInUsersCanDoAnything
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "${JENKINS_ADMIN_ID}"
          password: "${JENKINS_ADMIN_PASSWORD}"

unclassified:
  location:
    url: "http://localhost:8080/"
  globalNodeProperties:
    - envVars:
        env:
          - key: IMAGE_REPO
            value: "${IMAGE_REPO}"
          - key: KUBE_NAMESPACE
            value: "${KUBE_NAMESPACE}"
          - key: APP_REPO_URL
            value: "${APP_REPO_URL}"
          - key: APP_REPO_BRANCH
            value: "${APP_REPO_BRANCH}"
  sonar:
    installations:
      - name: "sonarqube"
        serverUrl: "http://sonarqube-ci:9000"
        credentialsId: "sonar-token"

credentials:
  system:
    domainCredentials:
      - domain: ""
        credentials:
          - usernamePassword:
              id: "dockerhub-creds"
              description: "Docker Hub username/password"
              scope: GLOBAL
              username: "${DOCKERHUB_USERNAME}"
              password: "${DOCKERHUB_TOKEN}"
          - string:
              id: "sonar-token"
              description: "SonarQube token"
              scope: GLOBAL
              secret: "${SONARQUBE_TOKEN}"

jobs:
  - script: "@/var/jenkins_home/casc/jobs/ci-cd-app.groovy"
